### ISSUE TITLE
Question about Enchantments obtainment

### ISSUE THREAD

**Issue by ConqAra** [IlMusu/IlMusuEnchantmentsMod#12]
These demonic enchantments cannot be obtained via trading/bartering from "enchant_randomly function, correct? I haven't tested yet but just in case they still do that should be looked into and prevented, as by default these demonic enchantments should only be obtainable through the demonic rituals.

**Comment by IlMusu** [comment]
The demonic enchantment are obtainable exclusively through the demonic enchanting mechanic. Neither villagers, chests, mobs with equipment should be able to provide those enchantments (except for the Phasing Enchantment which can be found in the ancient cities). Or at least, that is how it should work in the lastest version :')
