### ISSUE TITLE
Vein miner crashes the server

### ISSUE THREAD

**Issue by maciejkrol18** [IlMusu/IlMusuEnchantmentsMod#13]
If any player with a pickaxe enchanted with veinminer breaks a certain block, my server crashes. So far i'm sure it was caused by mining a cobblestone slab, an enderchest and an iron block. However, breaking regular cobblestone works fine - neither I nor the players have tested more blocks

<details>
<summary>Crash log</summary>
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-03-16 20:57:54
Description: Ticking entity

java.lang.ClassCastException: class com.ilmusu.musuen.enchantments.UnearthingEnchantment cannot be cast to class com.ilmusu.musuen.enchantments.VeinMinerEnchantment (com.ilmusu.musuen.enchantments.UnearthingEnchantment and com.ilmusu.musuen.enchantments.VeinMinerEnchantment are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @9629756)
	at com.ilmusu.musuen.enchantments.VeinMinerEnchantment.lambda$static$0(VeinMinerEnchantment.java:59)
	at com.ilmusu.musuen.callbacks.PlayerBreakSpeedCallback.lambda$static$0(PlayerBreakSpeedCallback.java:16)
	at net.minecraft.class_1657.localvar$bpp000$afterComputingBlockBreakingSpeed(class_1657.java:10014)
	at net.minecraft.class_1657.method_7351(class_1657.java:812)
	at net.minecraft.class_4970.method_9594(class_4970.java:394)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:852)
	at net.minecraft.class_3225.method_21716(class_3225.java:124)
	at net.minecraft.class_3225.method_14264(class_3225.java:117)
	at net.minecraft.class_3222.method_5773(class_3222.java:458)
	at net.minecraft.class_3218.track(class_3218.java:10735)
	at net.minecraft.class_3218.redirect$cci000$onTickNonPassenger(class_3218.java:10751)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.ilmusu.musuen.enchantments.VeinMinerEnchantment.lambda$static$0(VeinMinerEnchantment.java:59)
	at com.ilmusu.musuen.callbacks.PlayerBreakSpeedCallback.lambda$static$0(PlayerBreakSpeedCallback.java:16)
	at net.minecraft.class_1657.localvar$bpp000$afterComputingBlockBreakingSpeed(class_1657.java:10014)
	at net.minecraft.class_1657.method_7351(class_1657.java:812)
	at net.minecraft.class_4970.method_9594(class_4970.java:394)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:852)
	at net.minecraft.class_3225.method_21716(class_3225.java:124)
	at net.minecraft.class_3225.method_14264(class_3225.java:117)
	at net.minecraft.class_3222.method_5773(class_3222.java:458)
	at net.minecraft.class_3218.track(class_3218.java:10735)
	at net.minecraft.class_3218.redirect$cci000$onTickNonPassenger(class_3218.java:10751)
	at net.minecraft.class_3218.method_18762(class_3218.java:728)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 46479
	Entity Name: DragonFromRodos
	Entity's Exact location: -1242.57, 68.00, 166.87
	Entity's Block location: World: (-1243,68,166), Section: (at 5,4,6 in -78,4,10; chunk contains blocks -1248,-64,160 to -1233,319,175), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,-64,0 to -1025,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_3218.method_31420(class_3218.java:374)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:342)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 3 total; [class_3222['juuhc'/76932, l='ServerLevel[swiat]', x=-1241.20, y=68.00, z=168.39], class_3222['Iam_Osa'/96199, l='ServerLevel[swiat]', x=-1171.70, y=56.00, z=282.28], class_3222['DragonFromRodos'/46479, l='ServerLevel[swiat]', x=-1242.57, y=68.00, z=166.87]]
	Chunk stats: 7435
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,110,0), Section: (at 0,14,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 48788839 game time, 49507018 day time
	Level name: swiat
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 52057 (now: false), thunder time: 105259 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 5.15.0-67-generic
	Java Version: 17.0.6, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 3404626504 bytes (3246 MiB) / 5368709120 bytes (5120 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Device
	Graphics card #0 vendor: Vendor (0x1234)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x1111
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: RAM
	Virtual memory max (MB): 3974.98
	Virtual memory used (MB): 6466.35
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 20 total; -Xms5G -Xmx5G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		ad_astra: Ad Astra 1.13.4
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		alternate-current: Alternate Current 1.5.0
		antixray: AntiXray 1.3.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		architectury: Architectury 7.1.70
		axesareweapons: Axes Are Weapons 1.6.5
		azurelib: AzureLib 1.0.2
			com_eliotlash_mclib_mclib: mclib 20
		bluemap: BlueMap 3.10
		botarium: Botarium 2.0.4
			team_reborn_energy: Energy 2.2.0
		carryon: Carry On 2.0.4.15
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		collective: Collective 6.43
		debugify: Debugify 1.19.3+1.0
		dragonfight: Dragonfight Mod 1.19.3-3.7
		easyauth: Easy Authentication Mod 3.0.0-14
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mysql_mysql-connector-java: mysql-connector-java 8.0.29
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.0
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.0
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.0
			placeholder-api: Placeholder API 2.0.0-pre.2+1.19.3
			server_translations_api: Server Translations API 1.4.19+1.19.3
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		ecologics: Ecologics 2.1.12
		emojiful: Emojiful 4.1.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
			midnightlib: MidnightLib 1.0.0
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.5
		fabric-api: Fabric API 0.75.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.1+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		fallingtree: FallingTree 3.11.2
		ferritecore: FerriteCore 5.1.0
		followersteleporttoo: Followers Teleport Too 2.0
		friendsandfoes: Friends&Foes 1.8.0
		fwaystones: Fabric Waystones 3.0.6+mc1.19.3
		handcrafted: Handcrafted 2.0.4
		hwg: Happiness is a Warm Gun 1.3.3
		immersive_aircraft: Immersive Aircraft 0.3.0+1.19.3
		immersive_armors: Immersive Armors 1.5.4+1.19.3
		immersive_paintings: Immersive Paintings 0.5.0+1.19.3
		incendium: Incendium 5.1.4
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.0
		luckperms: LuckPerms 5.4.60
		memoryleakfix: memory Leak Fix 1.19.3-0.8.0
		minecraft: Minecraft 1.19.3
		mob_captains_mr: Mob Captains 1-v2.1.0
		moremobvariants: More Mob Variants 1.0.1
		musuen: IlMusu's Enchantments 1.1.3+fabric_1.19.3
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		nohostilesaroundcampfire: No Hostiles Around Campfire 5.0
		nounusedchunks: No Unused Chunks 1.3.2
			tcdcommons: TCD Commons API 2.0+1.19.3
		nullscape: Nullscape 1.2
		observable: Observable 4.3.1
		owo: oĎ‰o 0.10.2+1.19.3
			blue_endless_jankson: jankson 1.2.1
		plasmo_voice: Plasmo Voice 1.2.19
		powershot: Powershot 1.4.0-1.19.3-fabric
		resourcefulconfig: Resourcefulconfig 1.1.2
		resourcefullib: Resourceful Lib 1.2.7
			com_teamresourceful_yabn: yabn 1.0.2
		retraining: Retraining 1.2.0
		roughlyenoughitems: Roughly Enough Items 10.0.586
			error_notifier: Error Notifier 1.0.9
		rpgtitles_mr: RPGTitles 1.2.0
		servercore: ServerCore 1.3.4-1.19.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		skinrestorer: Skin Restorer 1.2.2
		smoothboot: Smooth Boot 1.19-1.7.1
		spark: spark 1.10.29
		spellbound_weapons_mr: Spellbound Weapons 4.0.1d
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		styledchat: Styled Chat 2.1.2+1.19.3
			player-data-api: Player Data API 0.2.2+1.19.3
			predicate-api: Predicate API 0.1.0+1.19.3
		the_bumblezone: The Bumblezone - Fabric 6.6.3+1.19.3-fabric
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			fake-player-api: Fake Player API 0.5.0
		tinycoal: Tiny Coal 1.1.0
		toms_storage: Tom's Simple Storage Mod 1.4.6
		totw_additions: Towers of the Wild: Additions 1.2.3
		travelersbackpack: Traveler's Backpack 1.19.3-8.3.2
		ultris_mr: Ultris: Boss Expansion 5.6.7f
		vanilla_refresh_mr: Vanilla Refresh 1.4.11b
		villagerdeathmessages: Villager Death Messages 3.1
		wilderwild: Wilder Wild 1.1.10-Fabric+1.19.3
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.1.11-Fabric+1.19.3
			nbtcrafting: NBT Crafting 2.2.3+mc1.19.3
		yet-another-config-lib: YetAnotherConfigLib 2.2.0
		yigd: You're in Grave Danger 1.5.1
	Server Running: true
	Player Count: 3 / 10; [class_3222['DragonFromRodos'/46479, l='ServerLevel[swiat]', x=-1242.57, y=68.00, z=166.87], class_3222['juuhc'/76932, l='ServerLevel[swiat]', x=-1241.20, y=68.00, z=168.39], class_3222['Iam_Osa'/96199, l='ServerLevel[swiat]', x=-1171.70, y=56.00, z=282.28]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
</details>

**Comment by IlMusu** [comment]
Please update the mod version, the issue is already solved in the newer versions
