### ISSUE TITLE
Nullpointer Crash When Opening Inventory

### ISSUE THREAD

**Issue by FreeMarcher** [IlMusu/IlMusuEnchantmentsMod#15]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-03-18 02:12:01
Description: Rendering screen

java.lang.NullPointerException: Cannot assign field "field_22764" because "this.musuen$pocketsButton" is null
	at net.minecraft.class_490.handler$ffd000$musuen$renderPocketSlots(class_490.java:2294)
	at net.minecraft.class_490.method_2389(class_490.java:111)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_490.handler$ffd000$musuen$renderPocketSlots(class_490.java:2294)
	at net.minecraft.class_490.method_2389(class_490.java:111)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_490.method_25394(class_490.java:90)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (171, 128). Absolute: (512.000000, 384.000000)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['FreeMarcher_'/152, l='ClientLevel', x=-282.88, y=65.00, z=-193.42]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,66,64), Section: (at 0,2,0 in -3,4,4; chunk contains blocks -48,-64,64 to -33,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 323989 game time, 1522 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, spoornpacks, Fabric Mods, Lum-5.2-1.19.zip, Rustic+Alternates.zip, 3d-goat-horn.zip, Better illagers - Extra Models Addon.zip, Better illagers - Witch Pets Addon.zip, Better illagers.zip, Villager_Variety-All_Mixed_[V1].zip, Retired_Wandering_Trader_(1.19).zip, Just Some More Bees v.1.0 1.19.zip, Better_Wolves_V2.1.zip, Healthy Salmon, biomedolphins.zip, betterturtlevariants-e110.zip, cart with donkey (chest donkey) (2).zip, too-many-cats.zip, s33r-more-parrots.zip, better-blazes-derpware.zip, biome-ravagers-1566450176.zip, drowned-variations.zip, os-default-skinned-zombies.zip, framedpanes-mc1-18-v2-0.zip, xalis Enhanced Wool v1.0.zip, better-candeles-e2580.zip, Enhanced Dripstone v1.1.zip, notes-e680.zip, Crystal_Sculk_sounds_and_fixes_update.zip, Cornetto's Cottagey Carpets.zip, nad-s-jukebox-v2-e2820.zip, henrys-better-sugar-cane.zip, moss.zip, remodeledcactus.zip, better-vines-16x-e1550.zip, cave-vines-16x-e1550.zip, Victoria Lily Pads copy, lichen-e2210.zip, nether-wart-e2280.zip, nether-wart-remaster-e1700.zip, PeridotGarden+Seagrass(v1.0).zip, ---BushyWarts---.zip, colorful-pumpkins-watermelons.zip, Ladytwilight's Flowering Crops, corality-1-0.zip, flowering-grass-and-roots.zip, §2Aesthetic+§4Bamboo.zip, §3BetterVanillaFoods§7_v1.12.6.zip, Immersive Weathering Generated Pack, immersive_weathering/biome_tinted_mossy_blocks, §2§lVisual§0-§a§lLeaf§0-§2§lDecay§0-§7§o1.3§0-§8.zip, Visual Titles.zip, diamonds in the sky.zip, end moon, Jeikir's Slime Variations.zip, rotated-skillet.zip, Everycomp Generated Pack, better_kelp

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4119623896 bytes (3928 MiB) / 7566524416 bytes (7216 MiB) up to 17985175552 bytes (17152 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37583.13
	Virtual memory used (MB): 23834.41
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 21.25
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17152m -Xms256m
	Fabric Mods: 
		adaptive-tooltips: Adaptive Tooltips 1.0.1
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		another_furniture: Another Furniture 2.1.2-1.19.2
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.69
		armordamagescale: Armor/Damage scale Mod 1.19.2-2.1
			com_ezylang_evalex: EvalEx 3.0.1
		attributefix: AttributeFix 17.2.6
		autoconfig1u: Auto Config v1 Updated 3.4.0
		balm-fabric: Balm 4.5.7
		bclib: BCLib 2.1.6
		beautify: Beautify 1.1.0+fabric-1.19.2
		bettercombat: Better Combat 1.6.2+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.4
		betterf3: BetterF3 4.0.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bodacious_berries: Bodacious Berries 2.0.7+mc1.19.2
			spruceui: SpruceUI 4.0.0+1.19
		bookshelf: Bookshelf 16.2.18
		bountiful: Bountiful 3.0.0
		boxtrot: The Box Trot 1.4
		brewinandchewin: Brewin And Chewin fabric-1.0.5+1.19.2
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		catalogue: Catalogue 1.7.0-1.19.2
		cave_enhancements: Cave Enhancements 1.19.2-2.1.11-fabric
		cem: Custom Entity Models 0.7.3-1.19
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		charmonium: Charmonium 4.2.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chefsdelight: Chef's Delight 1.0.2-fabric-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.53
		configured: Configured 2.0.0
		continuity: Continuity 2.0.2+1.19
		controlling: Controlling For Fabric 10.0+7
		copper_pipe: Simple Copper Pipes 1.12
		corgilib: CorgiLib 1.0.0.32
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		creativecore: CreativeCore (Fabric) 2.9.3
		creeperoverhaul: Creeper Overhaul 2.0.8
		crittersandcompanions: Critters and Companions 1.19.2-1.0.3
		cursery: Cursery Mod 1.19.2-3.1
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		debugify: Debugify 2.8.0
		deeper_oceans: Deeper Oceans 1.0
		deeperdarker: Deeper and Darker 1.1.6
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 3.0.2
				blue_endless_jankson: jankson 1.2.1
				org_yaml_snakeyaml: snakeyaml 1.27
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		draggable-resource-packs: Draggable Resource Packs 3.0.1+build.9
		driedbamboo: Dried Bamboo ${version}
		dualwield: DualWield 3.0.1-1.19
		duckling: Duckling 2.0.8
		dynmus: Dynamic Music 2.2.2+1.19.2
		earthtojavamobs: Earth2Java 1.9.3
		easyanvils: Easy Anvils 4.0.10
		ecologics: Ecologics 2.1.11
		edenring: EdenRing 0.6.4
		enchantwithmob: EnchantWithMob 1.19.2+1.1.0
		enchdesc: EnchantmentDescriptions 13.0.14
		enhancedcelestials: Enhanced Celestials 2.1.0.5
		entity_texture_features: Entity Texture Features 4.3.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		equipmentcompare: Equipment Compare 1.3.1
		everycomp: Every Compat 1.19.2-2.2.2
		explorerscompass: Explorer's Compass 1.19.2-2.2.0-fabric
		fabric-api: Fabric API 0.75.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.17
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		fantasticflowers: Fantastic Flowers 0.0.2-1.19.2
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersrespite: Farmer's Respite 2.2.4
			porting_lib: Porting Lib 2.1.656+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.656+1.19.2
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.656+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.656+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.656+1.19.2
				porting_lib_models: Porting Lib Models 2.1.656+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.656+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.656+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.656+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.656+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.656+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.656+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.656+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.656+1.19.2
						porting_lib_common: Porting Lib Common 2.1.656+1.19.2
		filtpick: FiltPick 1.0.0
			libgui: LibGui 6.4.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		fishofthieves: Fish of Thieves 2.2.2
		forgeconfigapiport: Forge Config API Port 4.2.11
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		giant_crops: Giant Crops ${version}
		goated: You've Goat to be kidding me 1.19.2-1.2.1
		iceberg: Iceberg 1.0.46
		immersive_aircraft: Immersive Aircraft 0.3.1+1.19.2
		immersive_armors: Immersive Armors 1.5.4+1.19.2
		immersive_weathering: Immersive Weathering 1.19.2-1.2.8
		impactfulweather: Biome Particle Weather 4.0.5
		incendium: Incendium 5.1.4
		indium: Indium 1.0.9+mc1.19.2
		interactic: Interactic 0.1.11+1.19
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		iron-jetpacks: Iron Jetpacks 0.4.5
			team_reborn_energy: Energy 2.3.0
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 4.0-1.19.2
		libertyvillagers: Liberty's Villagers 1.0.13+fabric+1.19.2
			server_translations_api: Server Translations API 1.4.18+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.11.1
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.0-1.19
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mobvote2022: Mob Vote 2022 1.0
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.2.19
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.2
			amecsapi: Amecs API 1.3.7+mc22w17a
			coat: Coat 1.0.0-beta.19+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc22w17a
		mushroom: Mushroom Update 1.0.0
		music_travels: Musical Travels 1.0.0
		musuen: IlMusu's Enchantments 1.2.1+fabric_1.19.2
			mm: Manningham Mills 2.3
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nethersdelight: Nether's Delight 1.0.1
			disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		nyfsquiver: Nyf's Quivers Fabric-0.5.1-1.19.2
			trinkets: Trinkets 3.5.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 4.2.4
		player-animator: Player Animator 1.0.2
		powershot: Powershot 1.4.0-1.19-fabric
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.3
		puzzleslib: Puzzles Lib 4.3.12
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		regions_unexplored: Regions Unexplored 0.3.1+1.19.2
		rfffpg: RFFFP Gemstones 0.0.4-1.19.2
		rottencreatures: Rotten Creatures 1.0.1
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughly_enough_trades: Roughly Enough Trades 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.595
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.4
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		saplanting: Saplanting 1.2.4
		sbmjukebox: SBM-Jukebox 1.0.7
		scout: Scout 1.1.2
		sihywtcamd: sihywtcamd 1.7.2+1.19
		simplyswords: Simply Swords 1.43.1-1.19.2
		smallships: Small Ships 2.0.0a1.1.1
		smoothswapping: Smooth Swapping 0.6
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		spoornarmorattributes: SpoornArmorAttributes 2.0.9-1.19
			net_objecthunter_exp4j: exp4j 0.4.8
		spoornpacks: SpoornPacks 4.3.3-1.19.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		spoornpink: Spoornpink 3.4.4-1.19
		spoornweaponattributes: SpoornWeaponAttributes 4.0.10-1.19
		spyglass_astronomy: Spyglass Astronomy 1.0.1-mc1.19.1+1.19.2
		structory: Structory 1.0.1
		takesapillage: Takes a Pillage 1.0.4
		tawct: Time & Wind Custom Ticker 1.4.3+1.19.2
		terrablender: TerraBlender 2.0.1.136
		themissingvillages: BigReefer's The Missing Villages Mod 2.0.0
		travelerstitles: Traveler's Titles 1.19.2-Fabric-3.1.0
		tree-hollows: Tree Hollows 1.5
			tree-hollows-main: Main 1.5
		treechop: HT's TreeChop 0.17.6
		vanilla_parts: Vanilla Parts 2.1.0+1.19.2
			blockstoparts: Blocks to Parts 0.3.0+1.19.2
			libmultipart_deps_container: LibMultiPart (Dependency Container) 0.8.0
				libblockattributes_core: LibBlockAttributes (Core) 0.11.1
				libmultipart: LibMultiPart 0.8.0
				libnetworkstack: Lib Network Stack 0.7.1
		varietyaquatic: varietyaquatic 1.0-SNAPSHOT
		vc_gliders: Gliders 1.0.1
			palladiumcore: PalladiumCore 1.19.2-1.2.3.4
		villagersplus: Villagers Plus 1.9
		wandering_collector: Wandering Collector 1.1.3+mc1.19
		waystones: Waystones 11.3.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: Custom (+31 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.17-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.49, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, spoornpacks, Fabric Mods, file/Lum-5.2-1.19.zip, file/Rustic+Alternates.zip (incompatible), file/3d-goat-horn.zip, file/Better illagers - Extra Models Addon.zip, file/Better illagers - Witch Pets Addon.zip, file/Better illagers.zip, file/Villager_Variety-All_Mixed_[V1].zip, file/Retired_Wandering_Trader_(1.19).zip, file/Just Some More Bees v.1.0 1.19.zip, file/Better_Wolves_V2.1.zip (incompatible), file/Healthy Salmon (incompatible), file/biomedolphins.zip (incompatible), file/betterturtlevariants-e110.zip (incompatible), file/cart with donkey (chest donkey) (2).zip, file/too-many-cats.zip, file/s33r-more-parrots.zip, file/better-blazes-derpware.zip (incompatible), file/biome-ravagers-1566450176.zip (incompatible), file/drowned-variations.zip (incompatible), file/os-default-skinned-zombies.zip (incompatible), file/framedpanes-mc1-18-v2-0.zip (incompatible), file/xalis Enhanced Wool v1.0.zip (incompatible), file/better-candeles-e2580.zip (incompatible), file/Enhanced Dripstone v1.1.zip (incompatible), file/notes-e680.zip (incompatible), file/Crystal_Sculk_sounds_and_fixes_update.zip, file/Cornetto's Cottagey Carpets.zip, file/nad-s-jukebox-v2-e2820.zip, file/henrys-better-sugar-cane.zip (incompatible), file/moss.zip (incompatible), file/remodeledcactus.zip (incompatible), file/better-vines-16x-e1550.zip (incompatible), file/cave-vines-16x-e1550.zip (incompatible), file/Victoria Lily Pads copy (incompatible), file/lichen-e2210.zip (incompatible), file/nether-wart-e2280.zip (incompatible), file/nether-wart-remaster-e1700.zip, file/PeridotGarden+Seagrass(v1.0).zip, file/---BushyWarts---.zip, file/colorful-pumpkins-watermelons.zip, file/Ladytwilight's Flowering Crops, file/corality-1-0.zip (incompatible), file/flowering-grass-and-roots.zip, file/§2Aesthetic+§4Bamboo.zip, file/§3BetterVanillaFoods§7_v1.12.6.zip, Immersive Weathering Generated Pack, immersive_weathering/biome_tinted_mossy_blocks, file/§2§lVisual§0-§a§lLeaf§0-§2§lDecay§0-§7§o1.3§0-§8.zip, file/Visual Titles.zip, file/diamonds in the sky.zip (incompatible), file/end moon (incompatible), file/Jeikir's Slime Variations.zip (incompatible), file/rotated-skillet.zip (incompatible), Everycomp Generated Pack, file/better_kelp
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['FreeMarcher_'/152, l='ServerLevel[Svarta]', x=-282.88, y=65.00, z=-193.42]]
	Data Packs: vanilla, Fabric Mods, Goated Generated Pack, Immersive Weathering Generated Pack, spoornpacks (incompatible), Everycomp Generated Pack
	World Generation: Stable

**Comment by IlMusu** [comment]
I'm not able to reproduce the error after installing all the mods in the list. Can you provide me the modpack?
