### ISSUE TITLE
Everlasting found in loot tables & on normal enchantment table

### ISSUE THREAD

**Issue by ConqAra** [IlMusu/IlMusuEnchantmentsMod#16]
Is this intended? There's two versions of Everlasting enchantment, one is Everlasting and the other is Everlasting Nulla (in fact, this is the case for every demonic enchantment!). What's the difference and why do I get everlasting in loot tables on enchanted gear and in normal enchantment tables?

**Comment by IlMusu** [comment]
The Everlasting enchantment is not a demonic enchantment. This means that, as any other enchantment, it can be found also outside the enchanting mechanic (ie in loot tables and gear).
I don't really know about the two versions of the enchantments, I've never seen something like that and I suspect there is another mod that is causing such behavior. Are you able to provide me more info? Such as the full NBT of the items containing the second version of the enchantment or maybe directly the modpack you are using?

**Comment by ConqAra** [comment]
<item:minecraft:enchanted_book>.withTag({StoredEnchantments: [{id: "musuen:everlasting" as string, lvl: 0 as short}]}) 
Item Tag Entries: <tag:items:deathknell:books>
![image](https://user-images.githubusercontent.com/76233356/227366821-879a9ddb-012c-4a57-88ba-ad74eecdc0fa.png)

Edit: Removed deathknell and nothing changed, idk whats causing this

**Comment by IlMusu** [comment]
That is very very strange and I feel like is something related to another mod. Btw, can you share the modpack so that we can solve this mystery?
Does that "Nulla" thing appear only on Jei or also in loot / enchanting table?

Edit: It is also strange that the level is 0, it should be 1 at minimum

**Comment by ConqAra** [comment]
Yeah sure: [https://www.dropbox.com/s/5220mrjwt34csuc/CanvasModPack.zip?dl=0](https://www.dropbox.com/s/5220mrjwt34csuc/CanvasModPack.zip?dl=0)

Fabric Loader 0.14.18
Java 18

or I made a repository of the modpack on my profile if that's easier for you
