### ISSUE TITLE
[Important suggestion[ Config to disable specific enchantments

### ISSUE THREAD

**Issue by ghost** [IlMusu/IlMusuEnchantmentsMod#19]
Some enchantments are too OP and they can destroy balance in Minecraft world with specific mods

**Comment by IlMusu** [comment]
I have already implemented a config file to disable the enchantments singularly.
You can also change the min and max levels for every enchantment (but some does not change at higher levels).
It is located at [minecraft_installation]/config/musuen/enchantments.properties
