### ISSUE TITLE
[1.19.4] Demonic Enchants incompatibility with "Enchancement" mod

### ISSUE THREAD

**Issue by ManicQuinn** [IlMusu/IlMusuEnchantmentsMod#20]
[Enhancement](https://modrinth.com/mod/enchancement) is a mod that overhauls the enchanting system so you can pick and choose what enchants you want, for the most part a lot of encahntments are removed, but you can configure it to bring back everything, which I did do. I can see one of the non-demonic enchants from this mod in there, which was DEMONCTION, but sadly not a single Demonic Enchantment. I also configured Enhancement to show curses and treasure enchants, no luck, also tested this mod without Enchancement, and the demonic enchants do appear, so it is a semi-conflict somewhat.

**Comment by IlMusu** [comment]
The reason behind the behaviour you are experiencing is how I coded the demonic enchantmenting:
In Vanilla, Minecraft generates a set of enchantments.
Then, I manually add the demonic enchantments to that set ONLY IF the skulls are around the enchanting table.
Given the description of [Enchantment](https://modrinth.com/mod/enchancement), it probably overhauls how the enchantments are generated and my checks regarding the skulls are never performed.
And this is the reason why the normals enchantments work but the demonic enchantments do not.

I feel like the only solution to solve these kinds of incompatibility is to change complitely the demonic enchanting and make a more comlicated mechanic which is behind the scope of this mod (for now).

**Comment by ManicQuinn** [comment]
That is fair, thanks for the response

**Comment by ManicQuinn** [comment]
A little update, I brought it up to the Enchancement Dev, they stated that there's only a single mixin to fix on your end, quote "it'd be a 1 mixin fix on their end, they'd just need to mixin here" : https://github.com/MoriyaShiine/enchancement/blob/e6768da283cb5bc965a9884305be9f67628d788d/src/main/java/moriyashiine/enchancement/common/screenhandlers/EnchantingTableScreenHandler.java#L253
