### ISSUE TITLE
[1.18.2] Phantoms spawning every night

### ISSUE THREAD

**Issue by ConqAra** [IlMusu/IlMusuEnchantmentsMod#24]
For some reason after updating this mod with the dreamlike enchantment phantoms start spawning every night on a regular basis even with no insomnia? Kinda ironic haha since the dreamlike enchantment was suppose to rid of that problem

**Comment by ConqAra** [comment]
Yeah I just tested and removed the mod on my server, phantoms arent spawning every night anymore. i also made sure to sleep every night so yeah really weird bug. probably has something to do with the new dreamlike enchantment

**Comment by IlMusu** [comment]
I realized I did a big mistake in the code and made phantoms spawn everywhere :,)
But I already fixed it... I will publish the new version today. Thank you!
