### ISSUE TITLE
[1.18.2] Incompatible with Better Enchantment Boosting Mod

### ISSUE THREAD

**Issue by ConqAra** [IlMusu/IlMusuEnchantmentsMod#8]
Mod: [https://modrinth.com/mod/better-enchantment-boosting](https://modrinth.com/mod/better-enchantment-boosting)
Demonic Enchanting doesn't appear if you're using Better Enchantment Boosting mod. I rerolled a ton of times and didn't encounter any demonic enchantments nor see any special glyphs around the table until I removed the mod in question.

![2023-03-10_20 32 46](https://user-images.githubusercontent.com/76233356/224457872-c46d9d0b-8323-461b-930c-7147694243dc.png)
![2023-03-10_20 32 48](https://user-images.githubusercontent.com/76233356/224457873-ca7520ba-0415-44c6-ab82-47404082032f.png)

**Comment by IlMusu** [comment]
I just verified that IlMusu's Enchantments is incompatible with Better Enchantment Boosting because of how they modified the vanilla code for the enchanting table. Unfortunately, there is not much that I can do about it without changing compitely the logic of demonic enchanting.
